import {
  RiBarChartBoxLine, RiMoneyDollarCircleLine, RiBuilding2Line, RiBuilding3Line,
  RiPercentLine, RiBookmarkLine, RiClipboardLine, RiRocketLine, RiScales3Line,
  RiEarthLine, RiLockPasswordLine, RiTrademarkLine, RiRestaurantLine, RiLineChartLine,
  RiTrophyLine, RiGlobalLine, RiWallet3Line, RiFlashlightFill, RiShieldCheckLine, RiCustomerService2Line,
  RiPhoneLine, RiFileTextLine, RiCheckDoubleLine
} from 'react-icons/ri';

// ═══════════════════════════════════════════════════════════
//  Accu Nex Taxation Services — Central Data Store
//  All content, services, FAQs, team, stats defined here.
//  Edit this file to update any content site-wide.
// ═══════════════════════════════════════════════════════════

// ─── BRAND CONFIG ───────────────────────────────────────────
export const BRAND = {
  name: 'Accu Nex Taxation Services',
  shortName: 'AccuNex',
  legalName: 'Accu Nex Taxation Services',
  tagline: 'Accurate. Reliable. Trusted CA Services',
  subTagline: "India's Trusted CA Partner for GST, ITR, Company Registration & More",
  description:
    'ICAI-registered CA firm providing GST registration & returns, ITR filing, company registration, TDS compliance, ROC filings, bookkeeping, and all CA services 100% online across India.',
  phone: '9999999999',          // ← replace with actual
  whatsapp: '919999999999',     // ← replace with actual (no +, no spaces)
  email: 'info@accunextaxation.com',
  address: 'India',
  city: 'India',
  website: 'https://accunextaxation.com',
  icai: 'ICAI Registered',
  yearEstablished: 2015,
  social: {
    facebook:  'https://www.facebook.com/accunextaxation',
    instagram: 'https://www.instagram.com/accunextaxation',
    linkedin:  'https://www.linkedin.com/company/accunextaxation',
    twitter:   'https://twitter.com/accunextaxation',
    youtube:   'https://www.youtube.com/@accunextaxation',
  }
}

// ─── SOCIAL LINKS (backward-compat alias) ───────────────────
export const SOCIAL_LINKS = {
  phone: BRAND.phone,
  email: BRAND.email,
  address: BRAND.address,
  location: BRAND.city,
  website: BRAND.website,
  facebook:  BRAND.social.facebook,
  twitter:   BRAND.social.twitter,
  instagram: BRAND.social.instagram,
  linkedin:  BRAND.social.linkedin,
}

// ─── STATS (animated counters) ──────────────────────────────
export const STATS = [
  { number: 500,   suffix: '+',  label: 'Happy Clients',      icon: '👥' },
  { number: 10000, suffix: '+',  label: 'Returns Filed',      icon: RiFileTextLine },
  { number: 10,    suffix: '+',  label: 'Years Experience',   icon: RiTrophyLine },
  { number: 4.9,   suffix: '★', label: 'Client Rating',      icon: '⭐' },
]

// ─── NAV ITEMS ───────────────────────────────────────────────
export const NAV_ITEMS = [
  { name: 'Home',     href: '/',         icon: 'fa-house' },
  { name: 'Services', href: '/#services', icon: 'fa-briefcase' },
  { name: 'About Us', href: '/about',    icon: 'fa-info-circle' },
  { name: 'Blog',     href: '/blog',     icon: 'fa-newspaper' },
  { name: 'Contact',  href: '/contact',  icon: 'fa-phone' },
]

// ─── SERVICES (14 CA services) ───────────────────────────────
export const SERVICES = [
  {
    id: 1,
    slug: 'gst-services',
    title: 'GST Services',
    shortTitle: 'GST',
    icon: 'fa-receipt',
    iconEmoji: '🧾',
    category: 'Tax Filing',
    isPopular: true,
    badge: 'Most Popular',
    shortDesc: 'Complete GST compliance — registration to annual returns, notices & audit.',
    overview:
      'Accu Nex provides end-to-end GST services for businesses of all sizes across India. From obtaining your GSTIN to filing monthly, quarterly, and annual returns, we handle everything on gst.gov.in. Our CA team ensures accurate GSTR-1, GSTR-3B, and GSTR-9/9C filings, maximising your ITC claims and keeping you penalty-free.',
    services: [
      'GST Registration (New, Amendment, Cancellation)',
      'GSTR-1 filing (monthly / quarterly)',
      'GSTR-3B filing with ITC reconciliation',
      'GSTR-9 — Annual Return',
      'GSTR-9C — Reconciliation Statement (GST Audit)',
      'LUT Application for exporters',
      'E-way bill generation & management',
      'GST notice response & assessments',
      'GST refund claims (exports, excess ITC)',
      'GST registration in multiple states',
    ],
    startingPrice: '₹999',
    timeline: '3–7 working days',
    whatsappMsg: 'Hi! I need GST Services from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 2,
    slug: 'income-tax',
    title: 'Income Tax / ITR Filing',
    shortTitle: 'ITR Filing',
    icon: 'fa-file-invoice-dollar',
    icon: RiMoneyDollarCircleLine,
    category: 'Tax Filing',
    isPopular: true,
    badge: 'Most Popular',
    shortDesc: 'ITR filing for individuals, businesses & professionals with maximum tax savings.',
    overview:
      'File your income tax return accurately and on time with Accu Nex. We handle ITR-1 through ITR-7, reconcile your AIS/26AS, maximise deductions under 80C, 80D, HRA, and more. Our CAs represent clients in tax notices, scrutiny assessments, and appeals before CIT and ITAT.',
    services: [
      'ITR-1 — Salaried individuals (salary, one house property)',
      'ITR-2 — Multiple properties, capital gains, foreign income',
      'ITR-3 — Business/professional income with accounts',
      'ITR-4 — Presumptive taxation (44AD, 44ADA, 44AE)',
      'ITR-5 to ITR-7 — Firms, companies, trusts',
      'AIS/26AS reconciliation',
      'Tax planning & advance tax computation',
      'Income tax notice handling & response',
      'Tax audit u/s 44AB (Form 3CA/3CB & 3CD)',
      'Appeals before CIT(A) and ITAT',
    ],
    startingPrice: '₹499',
    timeline: '1–3 working days',
    whatsappMsg: 'Hi! I need ITR filing assistance from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 3,
    slug: 'company-registration',
    title: 'Company Registration',
    shortTitle: 'Company Reg',
    icon: 'fa-building',
    icon: RiBuilding2Line,
    category: 'Business',
    isPopular: true,
    badge: 'High Demand',
    shortDesc: 'Private Limited, OPC, LLP, Partnership & Section 8 company incorporation.',
    overview:
      "Start your business the right way with Accu Nex. We handle complete company incorporation on MCA's SPICe+ portal — from name reservation and DIN/DSC to Certificate of Incorporation. No office visit required. We serve startups, SMEs, and entrepreneurs across India.",
    services: [
      'Private Limited Company (Pvt Ltd)',
      'One Person Company (OPC)',
      'Limited Liability Partnership (LLP)',
      'Partnership Firm Registration',
      'Sole Proprietorship',
      'Section 8 Company (NGO / Non-profit)',
      'Name reservation on MCA',
      'DIN & DSC procurement',
      'MOA / AOA / LLP Agreement drafting',
      'PAN & TAN application post-incorporation',
    ],
    startingPrice: '₹6,999',
    timeline: '7–15 working days',
    whatsappMsg: 'Hi! I want to register a company with Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 4,
    slug: 'msme-registration',
    title: 'MSME / Udyam Registration',
    shortTitle: 'MSME',
    icon: 'fa-industry',
    icon: RiBuilding3Line,
    category: 'Business',
    isPopular: false,
    badge: '',
    shortDesc: 'Udyam Registration on udyamregistration.gov.in for micro, small & medium enterprises.',
    overview:
      'MSME (Micro, Small & Medium Enterprise) registration through Udyam on udyamregistration.gov.in is free on the government portal. Accu Nex guides you through correct classification, documentation, and registration — unlocking benefits like priority lending, subsidies, lower interest rates, and government scheme eligibility.',
    services: [
      'Udyam Registration for new enterprises',
      'Migration from old UAM/EM-II to Udyam',
      'Classification as Micro / Small / Medium',
      'Amendment of Udyam certificate details',
      'MSME benefits consultation',
      'Government scheme eligibility check',
      'Bank loan facilitation with MSME certificate',
      'CGTMSE (collateral-free loan) guidance',
    ],
    startingPrice: '₹499',
    timeline: '1–2 working days',
    whatsappMsg: 'Hi! I need MSME/Udyam Registration from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 5,
    slug: 'tds-compliance',
    title: 'TDS / TCS Compliance',
    shortTitle: 'TDS Returns',
    icon: 'fa-percent',
    icon: RiBarChartBoxLine,
    category: 'Tax Filing',
    isPopular: false,
    badge: '',
    shortDesc: 'Quarterly TDS/TCS return filing, deduction computation & Form 16 issuance.',
    overview:
      'TDS (Tax Deducted at Source) compliance is mandatory for businesses deducting tax on salary, professional fees, rent, or contract payments. Accu Nex handles TDS computation, quarterly return filing (24Q, 26Q, 27EQ), default resolution, and issues Form 16 / 16A to employees and vendors.',
    services: [
      'TDS computation and payment (Challan 281)',
      '24Q — TDS on salary (quarterly)',
      '26Q — TDS on non-salary (quarterly)',
      '27EQ — TCS returns',
      '27Q — TDS on foreign payments',
      'Form 16 / 16A / 16B certificate generation',
      'TAN registration & corrections',
      'TDS default notice resolution',
      'Online TDS credit correction (TRACES)',
      'Lower deduction certificate u/s 197',
    ],
    startingPrice: '₹1,499',
    timeline: '2–5 working days',
    whatsappMsg: 'Hi! I need TDS/TCS compliance services from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 6,
    slug: 'accounting',
    title: 'Accounting & Bookkeeping',
    shortTitle: 'Accounting',
    icon: 'fa-book-open',
    icon: RiBookmarkLine,
    category: 'Compliance',
    isPopular: false,
    badge: '',
    shortDesc: 'Monthly bookkeeping, MIS reports, payroll processing & financial statement preparation.',
    overview:
      'Accurate books are the foundation of every successful business. Accu Nex provides monthly bookkeeping in Tally ERP/Prime and QuickBooks, reconciles bank statements, prepares MIS reports for management, and delivers audit-ready P&L and Balance Sheet. We also manage payroll, PF, and ESIC calculations.',
    services: [
      'Monthly bookkeeping in Tally ERP / QuickBooks',
      'Bank statement reconciliation',
      'Accounts payable & receivable management',
      'MIS reports (monthly / quarterly)',
      'Profit & Loss Account preparation',
      'Balance Sheet and Cash Flow Statement',
      'Payroll processing & salary slips',
      'PF / ESIC computation and filing',
      'GST-aligned bookkeeping with ITC reconciliation',
      'Year-end finalization for audit / ITR',
    ],
    startingPrice: '₹2,499/mo',
    timeline: 'Ongoing monthly',
    whatsappMsg: 'Hi! I need bookkeeping & accounting services from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 7,
    slug: 'roc-compliance',
    title: 'ROC Compliance',
    shortTitle: 'ROC Filings',
    icon: 'fa-landmark',
    iconEmoji: '🏛️',
    category: 'Compliance',
    isPopular: false,
    badge: '',
    shortDesc: 'Annual ROC filings — AOC-4, MGT-7, DIR-3 KYC, charge registration & more.',
    overview:
      'Every registered company must file annual returns and financial statements with the Registrar of Companies (ROC) via MCA. Accu Nex ensures timely filing of AOC-4, MGT-7, DIR-3 KYC, and other MCA forms, avoiding heavy late fees and director disqualification.',
    services: [
      'AOC-4 — Filing of financial statements',
      'MGT-7 / MGT-7A — Annual return',
      'DIR-3 KYC — Director KYC',
      'ADT-1 — Auditor appointment',
      'Share transfer SH-4 & SH-6 filings',
      'Charge creation / modification / satisfaction',
      'Board resolutions & minutes maintenance',
      'INC-20A — Business commencement',
      'Registered office change (INC-22)',
      'Company name change (INC-24)',
    ],
    startingPrice: '₹3,999/yr',
    timeline: 'Before due dates',
    whatsappMsg: 'Hi! I need ROC compliance services from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 8,
    slug: 'startup-services',
    title: 'Startup Services',
    shortTitle: 'Startup India',
    icon: 'fa-rocket',
    icon: RiRocketLine,
    category: 'Business',
    isPopular: false,
    badge: 'Growing Demand',
    shortDesc: 'Startup India registration, DPIIT recognition, 80-IAC tax exemption & funding support.',
    overview:
      "Get your startup recognised by DPIIT (Department for Promotion of Industry and Internal Trade) and unlock benefits including 3-year income tax exemption under Section 80-IAC, self-certification of compliances, fast-track patent/trademark processing, and Startup India Seed Fund Scheme eligibility. Accu Nex handles the complete Startup India application.",
    services: [
      'Startup India registration on startupindia.gov.in',
      'DPIIT recognition certificate',
      'Section 80-IAC tax exemption application (Inter-Ministerial Board)',
      'Section 56(2)(viib) angel tax exemption',
      'Startup India Seed Fund Scheme guidance',
      'Fund of Funds (FFS) eligibility',
      'Self-certification for 6 labour & 3 environment laws',
      'Fast-track IP (patent, trademark) assistance',
      'ESOP structuring for startups',
      'Compliance calendar for funded startups',
    ],
    startingPrice: '₹2,999',
    timeline: '7–15 working days',
    whatsappMsg: 'Hi! I need Startup India registration from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 9,
    slug: 'tax-notices',
    title: 'Tax Notices & Scrutiny',
    shortTitle: 'Tax Notices',
    icon: 'fa-shield-halved',
    iconEmoji: '🛡️',
    category: 'Tax Filing',
    isPopular: false,
    badge: '',
    shortDesc: 'Income tax & GST notice response, scrutiny assessment & appeals representation.',
    overview:
      'Receiving a tax notice can be stressful — but most notices are routine and can be resolved efficiently. Accu Nex handles all income tax and GST notices: intimation u/s 143(1), scrutiny u/s 143(3), survey u/s 133A, and high-value transaction queries. We draft professional responses, appear before assessing officers, and file appeals where necessary.',
    services: [
      'Income tax notice response (143(1), 142(1), 148)',
      'Scrutiny assessment u/s 143(3) representation',
      'Rectification u/s 154',
      'AIS/26AS mismatch resolution',
      'Demand stay applications',
      'CIT(A) — Commissioner of Income Tax (Appeals)',
      'ITAT — Income Tax Appellate Tribunal',
      'GST notice & demand response',
      'GST show cause notice (SCN) reply',
      'Penalty waiver & compounding applications',
    ],
    startingPrice: '₹2,499',
    timeline: 'Case-specific',
    whatsappMsg: 'Hi! I received a tax notice and need help from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 10,
    slug: 'iec-registration',
    title: 'IEC — Import Export Code',
    shortTitle: 'IEC / FEMA',
    icon: 'fa-globe',
    iconEmoji: '🌐',
    category: 'Business',
    isPopular: false,
    badge: '',
    shortDesc: 'Import Export Code registration on DGFT portal & FEMA compliance advisory.',
    overview:
      'An Import Export Code (IEC) is mandatory for any business importing or exporting goods or services from India. Accu Nex registers your IEC on the DGFT portal (dgft.gov.in) and assists with FEMA compliances for cross-border transactions, AD Code registration with banks, and export documentation.',
    services: [
      'IEC Registration on DGFT portal',
      'IEC modification & update',
      'IEC suspension revival',
      'AD Code registration with bank',
      'FEMA compliance advisory',
      'Softex / FIRC management',
      'Export incentives — RoDTEP, MEIS/SEIS',
      'Letter of Credit (LC) documentation',
      'Import duty calculation advisory',
      'Advance Authorisation / EPCG scheme guidance',
    ],
    startingPrice: '₹1,499',
    timeline: '3–5 working days',
    whatsappMsg: 'Hi! I need IEC registration from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 11,
    slug: 'dsc',
    title: 'Digital Signature (DSC)',
    shortTitle: 'DSC',
    icon: 'fa-signature',
    iconEmoji: '✍️',
    category: 'Compliance',
    isPopular: false,
    badge: '',
    shortDesc: 'Class 2 & Class 3 DSC procurement for MCA, tenders, GST, income tax filing.',
    overview:
      'A Digital Signature Certificate (DSC) is required for MCA company filing, income tax return by companies, GST registration, e-tendering, and DGFT. Accu Nex procures Class 2 and Class 3 DSCs from licensed Certifying Authorities with video KYC — delivered to your door or as a downloadable token.',
    services: [
      'Class 2 DSC — for individuals (ITR, MCA, GST)',
      'Class 3 DSC — for tenders (CPPP, GEM, NIC)',
      'Organisation DSC for company MCA filings',
      'DGFT DSC for import/export',
      'DSC renewal (expiry cases)',
      'PAN-based DSC (e-token format)',
      'Video KYC-based DSC issuance',
      'DSC revocation for compromised tokens',
    ],
    startingPrice: '₹799',
    timeline: '1–3 working days',
    whatsappMsg: 'Hi! I need a Digital Signature Certificate from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 12,
    slug: 'trademark',
    title: 'Trademark Registration',
    shortTitle: 'Trademark',
    icon: 'fa-trademark',
    icon: RiTrademarkLine,
    category: 'Business',
    isPopular: false,
    badge: '',
    shortDesc: 'TM-1 filing, objection reply, trademark renewal & IP protection across India.',
    overview:
      'Protect your brand name, logo, and tagline with trademark registration on ipindia.gov.in. Accu Nex conducts a prior art search, files TM-1 application under the appropriate class, responds to examination reports and objections, and handles trademark renewal — ensuring your brand IP is secure.',
    services: [
      'Trademark search & clearance report',
      'TM-1 application filing (single class)',
      'Multi-class trademark applications',
      'Trademark examination report reply',
      'Trademark objection reply',
      'TM hearing representation',
      'Trademark registration certificate',
      'Trademark renewal (TM-R)',
      'Trademark opposition response',
      'Brand name / logo advisory',
    ],
    startingPrice: '₹3,499',
    timeline: '3–24 months (process-dependent)',
    whatsappMsg: 'Hi! I want to register my trademark with Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1524673278499-6f657b8ba5ef?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 13,
    slug: 'fssai',
    title: 'FSSAI License',
    shortTitle: 'FSSAI',
    icon: 'fa-utensils',
    icon: RiRestaurantLine,
    category: 'Business',
    isPopular: false,
    badge: '',
    shortDesc: 'FSSAI basic registration, state & central license for food businesses.',
    overview:
      'Every food business operator (FBO) in India must obtain FSSAI (Food Safety and Standards Authority of India) registration or license before commencing operations. Accu Nex handles FSSAI basic registration, state license, and central license based on your turnover and operations — along with renewals and modifications.',
    services: [
      'FSSAI Basic Registration (turnover < ₹12 lakh)',
      'State License (₹12 lakh – ₹20 crore turnover)',
      'Central License (turnover > ₹20 crore / multi-state)',
      'FSSAI registration modification',
      'FSSAI license renewal',
      'FoSCoS portal registration',
      'Foster compliance advisory',
      'Food category consultation',
      'Annual returns (Form D-1)',
      'FSSAI display requirements guidance',
    ],
    startingPrice: '₹1,499',
    timeline: '7–30 working days',
    whatsappMsg: 'Hi! I need FSSAI registration/license from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&q=80&auto=format&fit=crop',
  },
  {
    id: 14,
    slug: 'project-reports',
    title: 'Project Reports & CMA',
    shortTitle: 'Project Reports',
    icon: 'fa-chart-line',
    icon: RiLineChartLine,
    category: 'Compliance',
    isPopular: false,
    badge: '',
    shortDesc: 'Bank loan project reports, CMA data, DPR preparation for MSME & startup funding.',
    overview:
      "A professionally prepared project report and CMA (Credit Monitoring Arrangement) data is essential for bank loan sanctions, MSME subsidies, and government scheme applications. Accu Nex prepares detailed project reports with financial projections, CMA data for CC/OD/term loans, and DPRs (Detailed Project Reports) aligned with banker's requirements.",
    services: [
      'Bank loan project report (term loan)',
      'CMA data preparation for CC / OD limits',
      'Detailed Project Report (DPR)',
      'Financial projections (5-year)',
      'MSME subsidy project reports',
      'Startup India / SIDBI funding reports',
      'PMEGP / MUDRA loan documentation',
      'Solar / renewable energy project DPR',
      'Stand-Up India loan report',
      'Break-even & sensitivity analysis',
    ],
    startingPrice: '₹2,999',
    timeline: '3–7 working days',
    whatsappMsg: 'Hi! I need a project report / CMA data from Accu Nex Taxation.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=700&q=80&auto=format&fit=crop',
  },
]

// ─── SERVICE CATEGORIES ──────────────────────────────────────
export const SERVICE_CATEGORIES = ['All', 'Tax Filing', 'Business', 'Compliance']

// ─── TEAM ────────────────────────────────────────────────────
export const TEAM = [
  {
    id: 1,
    name: 'CA [Name]',                         // ← Replace with actual CA name
    role: 'Founder & Principal Chartered Accountant',
    image: null,                                // ← Replace with actual image import
    expertise: 'GST, Income Tax, Company Law & ROC Compliance',
    qualification: 'B.Com, ACA (ICAI)',
    icai: 'MXXXXXX',                           // ← Replace with actual ICAI no.
    experience: '10+ years',
    phone: BRAND.phone,
    email: BRAND.email,
    featured: true,
  },
  {
    id: 2,
    name: 'CA [Name]',
    role: 'Senior Tax Consultant',
    image: null,
    expertise: 'Tax Audit, Corporate Tax, International Taxation',
    qualification: 'B.Com, ACA (ICAI)',
    icai: 'MXXXXXX',
    experience: '8+ years',
    phone: BRAND.phone,
    email: BRAND.email,
    featured: true,
  },
  {
    id: 3,
    name: '[Name]',
    role: 'GST & Compliance Specialist',
    image: null,
    expertise: 'GST, ROC, FSSAI, Trademark, Startup Services',
    qualification: 'B.Com, Semi-qualified CA',
    icai: '',
    experience: '5+ years',
    phone: BRAND.phone,
    email: BRAND.email,
    featured: true,
  },
]

// ─── FAQ ─────────────────────────────────────────────────────
export const FAQS = [
  {
    id: 1,
    q: 'What does GST registration cost at Accu Nex?',
    a: 'GST registration at Accu Nex starts at ₹999 (professional fee only). The government fee for GST registration on gst.gov.in is nil — it is completely free. Our fee covers documentation, ARN filing, query resolution, and follow-up until your GSTIN is issued, typically within 3–7 working days.',
  },
  {
    id: 2,
    q: 'What documents are required for ITR filing?',
    a: 'For salaried individuals: PAN, Aadhaar, Form 16, bank statements, and Form 26AS/AIS download from incometax.gov.in. For business owners: additionally P&L, Balance Sheet, GST returns, and TDS challans. Accu Nex sends you a personalised document checklist via WhatsApp once you contact us.',
  },
  {
    id: 3,
    q: 'How long does company registration take in India?',
    a: 'Private Limited Company registration typically takes 7–15 working days on MCA\'s SPICe+ portal. This covers DIN, DSC, name approval via RUN, and Certificate of Incorporation. Accu Nex handles the entire process online — no office visit required.',
  },
  {
    id: 4,
    q: 'Do I need a CA to file my income tax return?',
    a: 'Legally, individuals can file ITR-1/ITR-4 without a CA. However, a CA is mandatory for: tax audit u/s 44AB (business turnover > ₹1 crore / professional receipts > ₹50 lakh), statutory audit under Companies Act, and GSTR-9C. A CA also helps maximise deductions and avoid tax notices.',
  },
  {
    id: 5,
    q: 'What is the penalty for not filing GST returns?',
    a: 'Late GST return filing attracts: ₹50/day (₹25 CGST + ₹25 SGST) for regular returns, up to ₹5,000 maximum; ₹20/day (₹10 + ₹10) for NIL returns, up to ₹500. Additionally, 18% per annum interest applies on unpaid tax. Non-filing can result in GSTIN suspension.',
  },
  {
    id: 6,
    q: 'What is the GST registration turnover threshold in 2025?',
    a: 'GST registration is mandatory when annual aggregate turnover exceeds: ₹40 lakh for goods suppliers (₹20 lakh in special category states like Mizoram, Tripura, Meghalaya, etc.), ₹20 lakh for service providers (₹10 lakh in special states). E-commerce sellers and inter-state suppliers must register irrespective of turnover.',
  },
  {
    id: 7,
    q: 'What is MSME Udyam registration and is it really free?',
    a: 'Udyam Registration is the official MSME recognition on udyamregistration.gov.in. Government fee = ₹0 (completely free). Accu Nex charges only a professional fee for guidance and documentation. Benefits include priority bank lending, subsidy eligibility, lower interest rates, and protection under the MSMED Act.',
  },
  {
    id: 8,
    q: 'Can you handle tax notices received from the Income Tax Department?',
    a: 'Yes. Accu Nex handles all types of income tax notices: 143(1) intimations, 142(1) inquiries, 148 reassessment, and 133(6) information requests. We draft professional replies, represent before Assessing Officers, and file appeals before CIT(A) and ITAT where necessary.',
  },
  {
    id: 9,
    q: 'Are your CA services 100% online? Do I need to visit your office?',
    a: 'Yes, all services are 100% online. You share documents via WhatsApp, email, or our secure upload link. We prepare and file on your behalf and send acknowledgments digitally. No office visit is required for routine ITR, GST, TDS, registrations, or compliance filings.',
  },
  {
    id: 10,
    q: 'What are the fees for online CA services at Accu Nex?',
    a: 'Starting prices: GST Registration ₹999 | ITR Filing ₹499 | Company Registration ₹6,999 | TDS Return ₹1,499/qtr | Bookkeeping ₹2,499/mo | ROC Compliance ₹3,999/yr | MSME Registration ₹499. Government fees (MCA, stamp duty, etc.) are shown separately at actuals. We issue GST-compliant tax invoices.',
  },
]

// ─── WHY CHOOSE US ────────────────────────────────────────────
export const WHY_CHOOSE_US = [
  { icon: RiTrophyLine, title: 'ICAI Registered CAs', desc: 'All our Chartered Accountants are ICAI-registered with valid Certificate of Practice.' },
  { icon: RiGlobalLine, title: 'Pan-India Services', desc: '100% online — we serve clients in all 28 states and 8 UTs of India.' },
  { icon: RiWallet3Line, title: 'Transparent Pricing', desc: 'Fixed professional fees quoted upfront. Government fees shown separately at actuals. No hidden charges.' },
  { icon: RiFlashlightFill, title: 'Fast Turnaround', desc: 'ITR in 24 hours. GST registration in 3 days. Timely filing — always before due dates.' },
  { icon: RiShieldCheckLine, title: 'Secure & Confidential', desc: 'Your financial data is handled with complete confidentiality and shared only via secure channels.' },
  { icon: RiCustomerService2Line, title: 'Dedicated Support', desc: 'Dedicated relationship manager reachable on WhatsApp for real-time status updates.' },
]

// ─── PROCESS STEPS ───────────────────────────────────────────
export const PROCESS_STEPS = [
  {
    step: '01',
    icon: RiCustomerService2Line,
    title: 'Contact Us',
    desc: 'Reach out via WhatsApp, call, or our online form. Tell us your requirement.',
  },
  {
    step: '02',
    icon: RiFileTextLine,
    title: 'Share Documents',
    desc: 'We send a personalised checklist. You share documents via WhatsApp or email.',
  },
  {
    step: '03',
    icon: RiFlashlightFill,
    title: 'We Handle Everything',
    desc: 'Our CA prepares, verifies, and files on your behalf on government portals.',
  },
  {
    step: '04',
    icon: RiCheckDoubleLine,
    title: 'Done — Acknowledgment',
    desc: 'Receive your certificate / acknowledgment. We provide post-filing support too.',
  },
]

// ─── HERO SLIDES ─────────────────────────────────────────────
export const HERO_SLIDES = [
  {
    id: 1,
    badge: 'ICAI Registered CA Firm',
    heading: 'Expert CA Services',
    subHeading: 'Across India — Online & Fast',
    description:
      'GST registration, ITR filing, company incorporation & all compliance services delivered 100% online. 500+ clients. 10+ years experience.',
    ctaText: 'WhatsApp Us Now',
    ctaLink: `https://wa.me/${BRAND.whatsapp}?text=Hi! I need CA services from Accu Nex Taxation.`,
    ctaSecondary: 'Explore Services',
    ctaSecondaryLink: '/#services',
    backgroundImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1920&q=80&auto=format&fit=crop',
  },
  {
    id: 2,
    badge: 'GST • ITR • Company Registration',
    heading: 'All CA Services',
    subHeading: 'One Firm. Every Need.',
    description:
      'From GST returns to company incorporation, TDS compliance to trademark registration — complete CA solutions with transparent pricing.',
    ctaText: 'View Our Services',
    ctaLink: '/#services',
    ctaSecondary: 'Call Now',
    ctaSecondaryLink: `tel:${BRAND.phone}`,
    backgroundImage: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1920&q=80&auto=format&fit=crop',
  },
  {
    id: 3,
    badge: 'Free Consultation',
    heading: 'Book a Free',
    subHeading: 'Tax Consultation Today',
    description:
      'Talk to an ICAI-registered CA about your GST, income tax, or business registration needs. No obligation, no charges.',
    ctaText: 'Book Free Consultation',
    ctaLink: '/contact',
    ctaSecondary: 'Know More',
    ctaSecondaryLink: '/about',
    backgroundImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1920&q=80&auto=format&fit=crop',
  },
]

// ─── MARQUEE ITEMS ────────────────────────────────────────────
export const MARQUEE_ITEMS = [
  'GST Registration', 'ITR Filing', 'Company Registration', 'TDS Returns',
  'Bookkeeping', 'ROC Compliance', 'MSME Registration', 'Tax Notices',
  'IEC Registration', 'Digital Signature', 'Trademark Registration', 'FSSAI License',
  'Startup India', 'Project Reports', 'Tax Audit', 'GST Annual Return',
  'Income Tax Planning', 'CMA Data', 'DPIIT Recognition', 'PF & ESIC',
]

// ─── TESTIMONIALS ─────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rajesh Sharma',
    role: 'Business Owner',
    city: 'Delhi',
    rating: 5,
    text: 'Accu Nex handled my GST registration and monthly returns perfectly. Super fast response and transparent pricing. Highly recommended!',
  },
  {
    id: 2,
    name: 'Priya Mehta',
    role: 'Freelance Designer',
    city: 'Mumbai',
    rating: 5,
    text: 'I was confused about which ITR form to file. The team at Accu Nex guided me through everything online in just 2 days. Great service!',
  },
  {
    id: 3,
    name: 'Amit Agarwal',
    role: 'Startup Founder',
    city: 'Bangalore',
    rating: 5,
    text: 'From company registration to DPIIT recognition to 80-IAC application — Accu Nex handled everything. They\'re our go-to CA firm now.',
  },
  {
    id: 4,
    name: 'Sunita Devi',
    role: 'Restaurant Owner',
    city: 'Jaipur',
    rating: 5,
    text: 'Got my FSSAI license and GST registration done together. Very professional team, great communication on WhatsApp.',
  },
  {
    id: 5,
    name: 'Vikram Singh',
    role: 'Import Exporter',
    city: 'Ahmedabad',
    rating: 5,
    text: 'They handled my IEC registration, AD Code setup, and FEMA compliance. Very knowledgeable about international trade regulations.',
  },
  {
    id: 6,
    name: 'Neha Gupta',
    role: 'HR Manager',
    city: 'Pune',
    rating: 5,
    text: 'Our company\'s TDS returns, ROC filings, and bookkeeping are all managed by Accu Nex. Reliable, accurate, and always on time.',
  },
]

// ─── ABOUT SECTION ────────────────────────────────────────────
export const ABOUT = {
  title: 'About Accu Nex Taxation Services',
  subtitle: 'Your Trusted CA Partner Across India',
  description: `Accu Nex Taxation Services is an ICAI-registered Chartered Accountant firm committed to providing accurate, reliable, and client-focused CA services across India. Founded by experienced ICAI-qualified CAs, we have served 500+ clients with 10,000+ tax returns filed over 10+ years.

We provide all CA services 100% online — GST registration and returns, income tax filing, company incorporation, TDS compliance, ROC filings, bookkeeping, MSME registration, trademark, FSSAI, and more. Our approach is simple: transparent pricing, fast turnaround, and proactive communication via WhatsApp.`,
  highlights: [
    'ICAI Registered Chartered Accountants',
    '100% Online Services — Pan-India',
    'Transparent, Fixed Pricing',
    '500+ Happy Clients Served',
    'Fast Turnaround — Always Before Due Dates',
    'Dedicated WhatsApp Support',
  ],
  image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80&auto=format&fit=crop',
}
